name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-ubuntu:
    runs-on: [ self-hosted, ubuntu ]
    strategy:
      matrix:
        name: [ clang-12-debug, clang-12-release ]
        include:
          - name: clang-12-debug
            cc: clang-12
            cxx: clang++-12
            type: Debug
            tests: ON
          - name: clang-12-release
            cc: clang-12
            cxx: clang++-12
            type: Release
            tests: OFF
    steps:
      - name: Checkout the branch
        uses: actions/checkout@v2
        # See workaround for pull requests below
        if: ${{ github.event_name != 'pull_request' }}
        with:
          submodules: true

      - name: Checkout pull request head
        uses: actions/checkout@v2
        if: ${{ github.event_name == 'pull_request' }}
        with:
          # In case of pull requests $GITHUB_SHA contains random value
          # not existing in repository so use this hack to get true SHA
          ref: ${{ github.event.pull_request.head.sha }}
          submodules: true

      - name: Build Voxen
        run: |
          BUILD_DIR=$XDG_RUNTIME_DIR/voxen-builds/${{ matrix.name }}
          mkdir -p $BUILD_DIR
          rm -rf $BUILD_DIR/*
          cmake -S . -B $BUILD_DIR -GNinja             \
              -DCMAKE_C_COMPILER=${{ matrix.cc }}      \
              -DCMAKE_CXX_COMPILER=${{ matrix.cxx }}   \
              -DCMAKE_BUILD_TYPE=${{ matrix.type }}    \
              -DVOXEN_BUILD_TESTS=${{ matrix.tests }}
          cmake --build $BUILD_DIR -j12

      - name: Run simple tests
        if: matrix.tests == 'ON'
        run: |
          cd $XDG_RUNTIME_DIR/voxen-builds/${{ matrix.name }}
          ctest -j12
